number: '0123456789'
symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ €"
lang_char: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÉéЁЄІЈЉЎАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёђєіјљњћўџҐґӘҒҚҢӨҰҮІәғқңөұүі'
experiment_name: 'kz_synthtiger_v1'
train_data: '../../PaddleOCR_Mukhtar/train_data/rec/synthtiger/train_more'
valid_data: '../../PaddleOCR_Mukhtar/train_data/rec/synthtiger/test'
manualSeed: 1111
workers: 6
batch_size: 32 #32
num_iter: 1000
valInterval: 100
saved_model: '' #'saved_models/en_filtered/iter_300000.pth'
FT: False
optim: False # default is Adadelta
lr: 1.
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 5
#Data processing
select_data: 'images' # this is dataset folder in train_data
batch_ratio: '1' 
total_data_usage_ratio: 1.0
batch_max_length: 34 
imgH: 64
imgW: 600
rgb: False
contrast_adjust: False
sensitive: True
PAD: True
contrast_adjust: 0.0
data_filtering_off: False
# Model Architecture
Transformation: 'None'
FeatureExtraction: 'VGG'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False

network_params:
  input_channel: 1
  output_channel: 256
  hidden_size: 256
lang_list:
  - 'en'
character_list: 0123456789!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~ €ABCDEFGHIJKLMNOPQRSTUVWXYZӘҒҚҢӨҰҮІabcdefghijklmnopqrstuvwxyzәғқңөұүі